apiVersion: v1
kind: Service
metadata:
  labels:
    name: appserver
  name: appserver
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 7600
      targetPort: 7600   
  selector:
    app: appserver
---
kind: Service
apiVersion: v1
metadata:
  name: "my-mq"
spec:
  ports:
    - name: "my-mq"
      protocol: "TCP"
      port: 1414
      targetPort: 1414 
      nodePort: 0
  selector: {}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: "my-mq" 
subsets: 
  - addresses:
      - ip: "192.168.68.111" 
    ports:
      - port: 1414 
        name: "my-mq"