apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: appserver
        ports:
        - name: appserver
          containerPort: 7600
        env:  
          - name: "LICENSE" 
            value: "accept"
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mq
spec: 
  selector:
    matchLabels:
      app: my-mq
  template:
    metadata:
      labels:
        app: my-mq
    spec:
      containers:
        - name: "test-my-mq"
          image: "icr.io/ibm-messaging/mq"
          ports:
            - containerPort: 1414
              protocol: "TCP"
          env:
            - name: "LICENSE" 
              value: "accept"
             
---